---
development:
  cloud_name: <%= Rails.application.credentials.cloudinary.cloud_name %>
  api_key: <%= Rails.application.credentials.cloudinary.api_key %>
  api_secret: <%= Rails.application.credentials.cloudinary.api_secret %>
  enhance_image_tag: <%= Rails.application.credentials.cloudinary.enhance_image_tag %>
  static_file_support: <%= Rails.application.credentials.cloudinary.static_file_support %>

production:
  cloud_name: <%= Rails.application.credentials.cloudinary.cloud_name %>
  api_key: <%= Rails.application.credentials.cloudinary.api_key %>
  api_secret: <%= Rails.application.credentials.cloudinary.api_secret %>
  enhance_image_tag: <%= Rails.application.credentials.cloudinary.enhance_image_tag %>
  static_file_support: <%= Rails.application.credentials.cloudinary.static_file_support %>